# Generated by Django 3.2.9 on 2022-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
